export const browserCoreExamples = [
  "PowPow browser status",
  "PowPow browser start",
  "PowPow browser stop",
  "PowPow browser tabs",
  "PowPow browser open https://example.com",
  "PowPow browser focus abcd1234",
  "PowPow browser close abcd1234",
  "PowPow browser screenshot",
  "PowPow browser screenshot --full-page",
  "PowPow browser screenshot --ref 12",
  "PowPow browser snapshot",
  "PowPow browser snapshot --format aria --limit 200",
  "PowPow browser snapshot --efficient",
  "PowPow browser snapshot --labels",
];

export const browserActionExamples = [
  "PowPow browser navigate https://example.com",
  "PowPow browser resize 1280 720",
  "PowPow browser click 12 --double",
  'PowPow browser type 23 "hello" --submit',
  "PowPow browser press Enter",
  "PowPow browser hover 44",
  "PowPow browser drag 10 11",
  "PowPow browser select 9 OptionA OptionB",
  "PowPow browser upload /tmp/PowPow/uploads/file.pdf",
  'PowPow browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "PowPow browser dialog --accept",
  'PowPow browser wait --text "Done"',
  "PowPow browser evaluate --fn '(el) => el.textContent' --ref 7",
  "PowPow browser console --level error",
  "PowPow browser pdf",
];
